/* ══════════════════════════════════════════════════════════════════════
   WELLNESS SYNTHESIZER — Real-Time Health Concierge Engine
   
   Cross-references three biological domains:
   1. NUTRITION (Macros/Micros) — meal timing, glycemic load, protein pacing
   2. CIRCADIAN HEALTH — blue light, sleep architecture, cortisol rhythm
   3. HOLISTIC PRACTICES — sauna, cold plunge, breathwork, grounding
   
   When a disruption is detected in one domain (e.g., late-night meal),
   the Synthesizer propagates compensatory adjustments across the other
   two domains to maintain homeostatic equilibrium.
   
   Output: A prioritized queue of "Reactive Adjustments" — specific,
   timed protocol modifications that feel like a real-time health concierge.
   ══════════════════════════════════════════════════════════════════════ */

/* ══════════════════════════════════════════════════════════════════
   TYPES
   ══════════════════════════════════════════════════════════════════ */

export type SynthesizerDomain = 'nutrition' | 'circadian' | 'holistic';
export type DisruptionSeverity = 'mild' | 'moderate' | 'severe';
export type AdjustmentUrgency = 'immediate' | 'next_morning' | 'within_24h' | 'ongoing';

/** A detected disruption in one of the three domains */
export interface Disruption {
  id: string;
  domain: SynthesizerDomain;
  severity: DisruptionSeverity;
  signal: string;
  detail: string;
  detectedAt: number;
  /** Raw data that triggered this disruption */
  triggerData: Record<string, number | string | boolean>;
}

/** A compensatory adjustment generated by the Synthesizer */
export interface ReactiveAdjustment {
  id: string;
  /** Which disruption triggered this */
  disruptionId: string;
  /** Domain being adjusted (often different from disruption domain) */
  targetDomain: SynthesizerDomain;
  urgency: AdjustmentUrgency;
  /** Protocol modification title */
  title: string;
  /** Clinical reasoning */
  mechanism: string;
  /** Specific instruction */
  instruction: string;
  /** Icon for UI */
  icon: string;
  /** Accent color for severity */
  accentColor: string;
  /** Estimated time to execute (minutes) */
  durationMin: number;
  /** Suggested time of day */
  suggestedTime: string;
  /** Confidence score 0-100 */
  confidence: number;
  /** Which biomarkers this adjustment targets */
  targetBiomarkers: string[];
  /** Tags for filtering */
  tags: string[];
}

/** Full Synthesizer output */
export interface SynthesizerReport {
  disruptions: Disruption[];
  adjustments: ReactiveAdjustment[];
  /** Overall system coherence score 0-100 */
  coherenceScore: number;
  /** Natural language summary */
  conciergeMessage: string;
  /** Timestamp */
  synthesizedAt: number;
}

/** Input data for the Synthesizer */
export interface SynthesizerInput {
  /** Recent food logs (last 24h) */
  foodLogs: Array<{
    name: string;
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
    loggedAt: number;
  }>;
  /** Sleep data */
  sleep: {
    score?: number;
    hours?: number;
    deepPct?: number;
    remPct?: number;
    efficiency?: number;
    latencyMin?: number;
    bedtimeAt?: number;
    wakeAt?: number;
  };
  /** HRV data */
  hrv: {
    current?: number;
    avg7d?: number;
    trend?: string;
    baseline?: number;
  };
  /** Caffeine data */
  caffeine: {
    todayMg?: number;
    lastIntakeAt?: number;
    sensitivity?: boolean;
    dailyLimitMg?: number;
  };
  /** Protocol completions today */
  protocolsCompleted: Array<{
    name: string;
    category: string;
    completedAt: number;
  }>;
  /** Protocol logs (what was done) */
  protocolLogs: Array<{
    protocolName: string;
    category: string;
    loggedAt: number;
  }>;
  /** BioVault snapshot */
  bioVault: {
    crp?: number;
    hba1c?: number;
    vitaminD?: number;
    testosteroneTotal?: number;
    ferritin?: number;
    caffeineSensitivity?: boolean;
    mthfrVariant?: boolean;
    apoe4?: boolean;
  };
  /** Current time context */
  currentHour: number;
  /** User vitals */
  vitals?: {
    age?: number;
    weight?: number;
    gender?: string;
  };
}

/* ══════════════════════════════════════════════════════════════════
   DISRUPTION DETECTION RULES
   
   Each rule scans one domain for anomalies and returns a Disruption
   if the pattern matches. Rules are ordered by clinical priority.
   ══════════════════════════════════════════════════════════════════ */

interface DisruptionRule {
  id: string;
  domain: SynthesizerDomain;
  detect: (input: SynthesizerInput) => Disruption | null;
}

const DISRUPTION_RULES: DisruptionRule[] = [
  /* ── NUTRITION DISRUPTIONS ── */
  {
    id: 'late_night_meal',
    domain: 'nutrition',
    detect: (input) => {
      const lateFeedings = input.foodLogs.filter(f => {
        const hour = new Date(f.loggedAt).getHours();
        return hour >= 21 || hour < 4;
      });
      if (lateFeedings.length === 0) return null;
      const totalCals = lateFeedings.reduce((s, f) => s + f.calories, 0);
      const totalCarbs = lateFeedings.reduce((s, f) => s + f.carbs, 0);
      const severity: DisruptionSeverity = totalCarbs > 80 ? 'severe' : totalCals > 400 ? 'moderate' : 'mild';
      return {
        id: 'late_night_meal',
        domain: 'nutrition',
        severity,
        signal: 'Late-Night Feeding Window',
        detail: `${totalCals} kcal consumed after 9pm (${totalCarbs}g carbs). Elevated postprandial glucose during the melatonin window impairs insulin sensitivity by 15-20% and fragments deep sleep architecture via thermogenic interference.`,
        detectedAt: Date.now(),
        triggerData: { totalCals, totalCarbs, mealCount: lateFeedings.length },
      };
    },
  },
  {
    id: 'protein_deficit',
    domain: 'nutrition',
    detect: (input) => {
      const totalProtein = input.foodLogs.reduce((s, f) => s + f.protein, 0);
      const targetProtein = input.vitals?.weight ? input.vitals.weight * 0.82 : 130; // 0.82g/lb
      if (totalProtein >= targetProtein * 0.7) return null;
      const pctDeficit = Math.round((1 - totalProtein / targetProtein) * 100);
      return {
        id: 'protein_deficit',
        domain: 'nutrition',
        severity: pctDeficit > 50 ? 'severe' : 'moderate',
        signal: 'Protein Pacing Deficit',
        detail: `${totalProtein}g protein logged vs ${Math.round(targetProtein)}g target (${pctDeficit}% deficit). Muscle protein synthesis requires leucine threshold hits every 3-4h. Current pacing is insufficient for anabolic signaling.`,
        detectedAt: Date.now(),
        triggerData: { totalProtein, targetProtein: Math.round(targetProtein), pctDeficit },
      };
    },
  },
  {
    id: 'glycemic_spike_risk',
    domain: 'nutrition',
    detect: (input) => {
      const highCarbMeals = input.foodLogs.filter(f => f.carbs > 60 && f.protein < 20);
      if (highCarbMeals.length === 0) return null;
      const worstMeal = highCarbMeals.sort((a, b) => b.carbs - a.carbs)[0];
      const hba1cRisk = input.bioVault.hba1c != null && input.bioVault.hba1c > 5.5;
      return {
        id: 'glycemic_spike_risk',
        domain: 'nutrition',
        severity: hba1cRisk ? 'severe' : 'moderate',
        signal: 'Glycemic Load Alert',
        detail: `"${worstMeal.name}" logged with ${worstMeal.carbs}g carbs and only ${worstMeal.protein}g protein — high glycemic load without protein buffering causes rapid glucose spike → crash cycle.${hba1cRisk ? ` HbA1c at ${input.bioVault.hba1c}% amplifies metabolic risk.` : ''}`,
        detectedAt: Date.now(),
        triggerData: { carbsG: worstMeal.carbs, proteinG: worstMeal.protein, mealName: worstMeal.name },
      };
    },
  },

  /* ── CIRCADIAN DISRUPTIONS ── */
  {
    id: 'sleep_debt',
    domain: 'circadian',
    detect: (input) => {
      if (input.sleep.hours == null || input.sleep.hours >= 7) return null;
      const deficit = 7.5 - input.sleep.hours;
      const severity: DisruptionSeverity = input.sleep.hours < 5.5 ? 'severe' : input.sleep.hours < 6.5 ? 'moderate' : 'mild';
      return {
        id: 'sleep_debt',
        domain: 'circadian',
        severity,
        signal: 'Sleep Architecture Deficit',
        detail: `${input.sleep.hours.toFixed(1)}h sleep (${deficit.toFixed(1)}h below target). ${input.sleep.deepPct != null && input.sleep.deepPct < 15 ? `Deep sleep at ${input.sleep.deepPct}% — below 15% threshold for adequate growth hormone pulsatility. ` : ''}Cortisol clearance is compromised, elevating inflammatory markers for 24-48h.`,
        detectedAt: Date.now(),
        triggerData: { hours: input.sleep.hours, deficit, deepPct: input.sleep.deepPct ?? 0, score: input.sleep.score ?? 0 },
      };
    },
  },
  {
    id: 'late_caffeine',
    domain: 'circadian',
    detect: (input) => {
      if (input.caffeine.lastIntakeAt == null) return null;
      const intakeHour = new Date(input.caffeine.lastIntakeAt).getHours();
      const cutoffHour = input.caffeine.sensitivity ? 11 : 14;
      if (intakeHour < cutoffHour) return null;
      const halfLife = input.caffeine.sensitivity ? 8 : 5;
      return {
        id: 'late_caffeine',
        domain: 'circadian',
        severity: input.caffeine.sensitivity ? 'severe' : 'moderate',
        signal: 'Caffeine-Circadian Conflict',
        detail: `Caffeine intake at ${intakeHour}:00 (cutoff: ${cutoffHour}:00${input.caffeine.sensitivity ? ', CYP1A2 slow metabolizer' : ''}). With a ${halfLife}h half-life, ~50% of adenosine receptors will still be blocked at bedtime, reducing deep sleep by 15-25%.`,
        detectedAt: Date.now(),
        triggerData: { intakeHour, cutoffHour, halfLife, sensitivity: input.caffeine.sensitivity ?? false },
      };
    },
  },
  {
    id: 'late_bedtime',
    domain: 'circadian',
    detect: (input) => {
      if (input.sleep.bedtimeAt == null) return null;
      const bedHour = new Date(input.sleep.bedtimeAt).getHours();
      const adjustedHour = bedHour < 6 ? bedHour + 24 : bedHour;
      if (adjustedHour < 24) return null; // before midnight is fine
      const hoursLate = adjustedHour - 23;
      return {
        id: 'late_bedtime',
        domain: 'circadian',
        severity: hoursLate > 2 ? 'severe' : 'moderate',
        signal: 'Circadian Phase Delay',
        detail: `Bedtime at ${bedHour < 6 ? bedHour : bedHour}:00 — ${hoursLate.toFixed(1)}h past optimal window. Melatonin onset occurs ~9pm; sleeping past midnight misses the first deep sleep cycle and reduces growth hormone secretion by 30-50%.`,
        detectedAt: Date.now(),
        triggerData: { bedHour, hoursLate },
      };
    },
  },

  /* ── HOLISTIC DISRUPTIONS ── */
  {
    id: 'recovery_protocol_gap',
    domain: 'holistic',
    detect: (input) => {
      const recoveryProtocols = input.protocolsCompleted.filter(p =>
        ['biohacking', 'recovery'].includes(p.category)
      );
      const hrvDepressed = input.hrv.current != null && input.hrv.avg7d != null &&
        input.hrv.current < input.hrv.avg7d * 0.85;
      if (recoveryProtocols.length > 0 || !hrvDepressed) return null;
      const pctBelow = input.hrv.avg7d ? Math.round(((input.hrv.avg7d - (input.hrv.current ?? 0)) / input.hrv.avg7d) * 100) : 0;
      return {
        id: 'recovery_protocol_gap',
        domain: 'holistic',
        severity: pctBelow > 20 ? 'severe' : 'moderate',
        signal: 'Recovery Protocol Gap',
        detail: `HRV ${pctBelow}% below baseline at ${input.hrv.current}ms with zero recovery protocols logged today. Parasympathetic tone requires active intervention — passive rest alone is insufficient for autonomic recovery.`,
        detectedAt: Date.now(),
        triggerData: { hrvCurrent: input.hrv.current ?? 0, hrvAvg: input.hrv.avg7d ?? 0, pctBelow },
      };
    },
  },
  {
    id: 'inflammation_no_cold',
    domain: 'holistic',
    detect: (input) => {
      const crpHigh = input.bioVault.crp != null && input.bioVault.crp > 1.5;
      const coldDone = input.protocolLogs.some(p =>
        p.protocolName.toLowerCase().includes('cold') ||
        p.protocolName.toLowerCase().includes('plunge') ||
        p.protocolName.toLowerCase().includes('ice')
      );
      if (!crpHigh || coldDone) return null;
      return {
        id: 'inflammation_no_cold',
        domain: 'holistic',
        severity: input.bioVault.crp! > 3 ? 'severe' : 'moderate',
        signal: 'Inflammatory Load Without Cold Exposure',
        detail: `hs-CRP at ${input.bioVault.crp!.toFixed(1)} mg/L with no cold exposure logged. Cold immersion triggers norepinephrine release (200-300% increase) which directly suppresses NF-κB inflammatory signaling.`,
        detectedAt: Date.now(),
        triggerData: { crp: input.bioVault.crp!, coldDone: false },
      };
    },
  },
  {
    id: 'no_sunlight_protocol',
    domain: 'holistic',
    detect: (input) => {
      const sunlightDone = input.protocolLogs.some(p =>
        p.protocolName.toLowerCase().includes('sun') ||
        p.protocolName.toLowerCase().includes('light')
      );
      const vitDLow = input.bioVault.vitaminD != null && input.bioVault.vitaminD < 40;
      if (sunlightDone || !vitDLow) return null;
      return {
        id: 'no_sunlight_protocol',
        domain: 'holistic',
        severity: input.bioVault.vitaminD! < 25 ? 'severe' : 'mild',
        signal: 'Photonic Deficit',
        detail: `Vitamin D at ${input.bioVault.vitaminD} ng/mL with no morning sunlight protocol. Morning light exposure within 30min of waking sets the cortisol awakening response and anchors the circadian master clock (SCN).`,
        detectedAt: Date.now(),
        triggerData: { vitaminD: input.bioVault.vitaminD!, sunlightDone: false },
      };
    },
  },
];

/* ══════════════════════════════════════════════════════════════════
   REACTIVE ADJUSTMENT GENERATORS
   
   Each generator takes a Disruption and produces one or more
   compensatory adjustments across domains. This is where the
   "concierge" magic happens — a nutrition disruption triggers
   circadian and holistic adjustments.
   ══════════════════════════════════════════════════════════════════ */

type AdjustmentGenerator = (disruption: Disruption, input: SynthesizerInput) => ReactiveAdjustment[];

const ADJUSTMENT_MAP: Record<string, AdjustmentGenerator> = {
  /* ── Late Night Meal → Morning Recovery Protocol ── */
  late_night_meal: (d, input) => {
    const adjustments: ReactiveAdjustment[] = [];
    const carbsG = (d.triggerData.totalCarbs as number) ?? 0;

    // 1. Glucose-clearing walk (CIRCADIAN adjustment for NUTRITION disruption)
    adjustments.push({
      id: `${d.id}_glucose_walk`,
      disruptionId: d.id,
      targetDomain: 'circadian',
      urgency: 'next_morning',
      title: 'Glucose-Clearing Walk',
      mechanism: 'Post-prandial glucose from late feeding persists into morning. A fasted walk activates GLUT4 transporters via muscle contraction, clearing residual glucose without insulin. This resets insulin sensitivity for the day.',
      instruction: `20-minute brisk walk before breakfast. Fasted state required — water only. Target HR 100-120 BPM (Zone 1-2). This clears ${Math.round(carbsG * 0.3)}g of residual glycogen from last night's ${carbsG}g carb load.`,
      icon: '🚶',
      accentColor: '#00DC82',
      durationMin: 20,
      suggestedTime: '7:00 AM',
      confidence: 92,
      targetBiomarkers: ['hba1c', 'glucose'],
      tags: ['glucose', 'fasted', 'morning', 'movement'],
    });

    // 2. Delayed caffeine (CIRCADIAN adjustment)
    adjustments.push({
      id: `${d.id}_delay_caffeine`,
      disruptionId: d.id,
      targetDomain: 'circadian',
      urgency: 'next_morning',
      title: 'Delay Caffeine 90min',
      mechanism: 'Late-night eating elevates cortisol into the morning. Adding caffeine to an already-elevated cortisol state causes adrenal overstimulation and crashes by 2pm. Delaying caffeine allows the natural cortisol awakening response to clear first.',
      instruction: `No caffeine until ${input.caffeine.sensitivity ? '10:00 AM' : '9:30 AM'}. Drink 500mL water with a pinch of sea salt first. This allows cortisol to peak and decline naturally before caffeine amplifies it.`,
      icon: '☕',
      accentColor: '#E8976C',
      durationMin: 0,
      suggestedTime: input.caffeine.sensitivity ? '10:00 AM' : '9:30 AM',
      confidence: 88,
      targetBiomarkers: ['cortisol'],
      tags: ['caffeine', 'cortisol', 'timing'],
    });

    // 3. Extended morning fast (NUTRITION self-correction)
    if (carbsG > 50) {
      adjustments.push({
        id: `${d.id}_extended_fast`,
        disruptionId: d.id,
        targetDomain: 'nutrition',
        urgency: 'next_morning',
        title: 'Extended Morning Fast',
        mechanism: `Last night's ${carbsG}g carb load requires extended insulin clearance. Pushing first meal to noon creates a 14-16h fasting window that activates AMPK, upregulates autophagy, and restores insulin receptor sensitivity.`,
        instruction: 'Push first meal to 12:00 PM. Black coffee (after 90min delay) and water are permitted. First meal should be protein-forward (40g+) with healthy fats to prevent a second glucose spike.',
        icon: '⏰',
        accentColor: '#3B82F6',
        durationMin: 0,
        suggestedTime: '12:00 PM',
        confidence: 85,
        targetBiomarkers: ['hba1c', 'glucose', 'insulin'],
        tags: ['fasting', 'insulin', 'autophagy'],
      });
    }

    return adjustments;
  },

  /* ── Protein Deficit → Compensatory Pacing ── */
  protein_deficit: (d, input) => {
    const deficit = (d.triggerData.pctDeficit as number) ?? 30;
    const targetG = (d.triggerData.targetProtein as number) ?? 130;
    const currentG = (d.triggerData.totalProtein as number) ?? 0;
    const remainingG = targetG - currentG;
    const mealsLeft = input.currentHour < 12 ? 3 : input.currentHour < 17 ? 2 : 1;
    const perMealG = Math.round(remainingG / Math.max(mealsLeft, 1));

    return [{
      id: `${d.id}_protein_catch`,
      disruptionId: d.id,
      targetDomain: 'nutrition',
      urgency: 'immediate',
      title: 'Protein Pacing Recovery',
      mechanism: `Muscle protein synthesis requires ~40g leucine-rich protein every 3-4h to maintain anabolic signaling. Current ${currentG}g is ${deficit}% below target. Concentrated protein in remaining meals can partially recover the deficit.`,
      instruction: `Target ${perMealG}g protein per remaining meal (${mealsLeft} meals left). Prioritize: chicken breast (31g/100g), Greek yogurt (17g/cup), whey isolate (25g/scoop). Add 3g leucine to each meal for mTOR activation.`,
      icon: '🥩',
      accentColor: '#FF6B6B',
      durationMin: 0,
      suggestedTime: 'Next meal',
      confidence: 90,
      targetBiomarkers: ['testosteroneTotal', 'ferritin'],
      tags: ['protein', 'anabolic', 'leucine'],
    }];
  },

  /* ── Glycemic Spike → Post-Meal Protocol ── */
  glycemic_spike_risk: (d, input) => {
    const adjustments: ReactiveAdjustment[] = [];
    adjustments.push({
      id: `${d.id}_postmeal_walk`,
      disruptionId: d.id,
      targetDomain: 'holistic',
      urgency: 'immediate',
      title: 'Post-Meal Glucose Walk',
      mechanism: 'Walking within 15min of a high-carb meal activates skeletal muscle GLUT4 transporters, pulling glucose from blood into muscle cells without insulin. Studies show a 10-15min walk reduces postprandial glucose by 30-50%.',
      instruction: '10-15 minute walk immediately after the high-carb meal. Moderate pace — conversational. Even standing and light movement helps. This is the single most effective glucose-lowering intervention.',
      icon: '🚶‍♂️',
      accentColor: '#00DC82',
      durationMin: 15,
      suggestedTime: 'Immediately after meal',
      confidence: 95,
      targetBiomarkers: ['hba1c', 'glucose'],
      tags: ['glucose', 'postprandial', 'movement'],
    });

    if (input.bioVault.hba1c != null && input.bioVault.hba1c > 5.5) {
      adjustments.push({
        id: `${d.id}_berberine`,
        disruptionId: d.id,
        targetDomain: 'nutrition',
        urgency: 'within_24h',
        title: 'Berberine Protocol',
        mechanism: `HbA1c at ${input.bioVault.hba1c}% indicates chronic glucose dysregulation. Berberine activates AMPK (same pathway as metformin) and improves insulin sensitivity. 500mg before high-carb meals reduces glucose AUC by 25-35%.`,
        instruction: 'Add Berberine 500mg 15min before meals containing >40g carbs. Take with food. Do not combine with metformin without physician guidance.',
        icon: '💊',
        accentColor: '#AF82FF',
        durationMin: 0,
        suggestedTime: 'Before next high-carb meal',
        confidence: 82,
        targetBiomarkers: ['hba1c'],
        tags: ['supplement', 'glucose', 'AMPK'],
      });
    }

    return adjustments;
  },

  /* ── Sleep Debt → Multi-Domain Recovery ── */
  sleep_debt: (d, input) => {
    const adjustments: ReactiveAdjustment[] = [];
    const hours = (d.triggerData.hours as number) ?? 6;

    // Holistic: NSDR session
    adjustments.push({
      id: `${d.id}_nsdr`,
      disruptionId: d.id,
      targetDomain: 'holistic',
      urgency: 'immediate',
      title: 'NSDR Recovery Protocol',
      mechanism: `${hours.toFixed(1)}h sleep creates a recovery debt. Non-Sleep Deep Rest (NSDR/Yoga Nidra) activates parasympathetic dominance and increases dopamine by 65% without adenosine buildup. 20min NSDR = ~2h of restorative benefit.`,
      instruction: 'Perform 20-minute NSDR session between 1-3pm. Lie flat, eyes closed, follow guided body scan. This is NOT a nap — it maintains wakefulness while achieving deep parasympathetic recovery.',
      icon: '🧘',
      accentColor: '#AF82FF',
      durationMin: 20,
      suggestedTime: '1:00 PM - 3:00 PM',
      confidence: 91,
      targetBiomarkers: ['cortisol'],
      tags: ['nsdr', 'recovery', 'parasympathetic'],
    });

    // Nutrition: Anti-inflammatory support
    adjustments.push({
      id: `${d.id}_anti_inflam`,
      disruptionId: d.id,
      targetDomain: 'nutrition',
      urgency: 'immediate',
      title: 'Anti-Inflammatory Nutrition Stack',
      mechanism: 'Sleep deprivation elevates IL-6 and TNF-α within 24h. Omega-3 fatty acids (EPA/DHA) directly compete with arachidonic acid in the COX-2 pathway, reducing inflammatory prostaglandin synthesis.',
      instruction: 'Double Omega-3 dose today (4g EPA/DHA). Add turmeric/curcumin 1000mg with black pepper. Avoid refined sugar and seed oils — they amplify the inflammatory cascade from sleep debt.',
      icon: '🐟',
      accentColor: '#00FFCC',
      durationMin: 0,
      suggestedTime: 'With meals',
      confidence: 87,
      targetBiomarkers: ['crp'],
      tags: ['omega3', 'anti-inflammatory', 'supplement'],
    });

    // Circadian: Early bedtime tonight
    adjustments.push({
      id: `${d.id}_early_bed`,
      disruptionId: d.id,
      targetDomain: 'circadian',
      urgency: 'within_24h',
      title: 'Circadian Reset — Early Bedtime',
      mechanism: `${(7.5 - hours).toFixed(1)}h sleep debt requires aggressive recovery. One night of 9h sleep can recover ~70% of accumulated debt. Melatonin production peaks at 9-10pm — aligning bedtime with this window maximizes deep sleep.`,
      instruction: 'Screen-off at 8:30pm. Magnesium Glycinate 400mg at 9pm. Room temp 65-68°F. Target lights-out by 9:30pm for 9+ hours of sleep opportunity.',
      icon: '🌙',
      accentColor: '#3B82F6',
      durationMin: 0,
      suggestedTime: '8:30 PM',
      confidence: 93,
      targetBiomarkers: ['cortisol', 'testosteroneTotal'],
      tags: ['sleep', 'circadian', 'melatonin'],
    });

    return adjustments;
  },

  /* ── Late Caffeine → Circadian Repair ── */
  late_caffeine: (d, input) => [{
    id: `${d.id}_caffeine_flush`,
    disruptionId: d.id,
    targetDomain: 'holistic',
    urgency: 'immediate',
    title: 'Caffeine Clearance Protocol',
    mechanism: 'L-theanine (200mg) modulates caffeine\'s stimulatory effects by increasing alpha brain wave activity without blocking adenosine. Combined with magnesium, it accelerates the transition to parasympathetic dominance before sleep.',
    instruction: `Take L-Theanine 200mg now + Magnesium Glycinate 400mg at 8pm. Avoid all screens after 9pm. ${input.caffeine.sensitivity ? 'Your CYP1A2 variant means caffeine persists 60% longer — tomorrow, hard cutoff at 10am.' : 'Tomorrow, enforce caffeine cutoff at 12pm.'}`,
    icon: '🍵',
    accentColor: '#00DC82',
    durationMin: 0,
    suggestedTime: 'Now + 8:00 PM',
    confidence: 86,
    targetBiomarkers: ['cortisol'],
    tags: ['caffeine', 'l-theanine', 'sleep'],
  }],

  /* ── Late Bedtime → Morning Anchor ── */
  late_bedtime: (d) => [{
    id: `${d.id}_morning_anchor`,
    disruptionId: d.id,
    targetDomain: 'circadian',
    urgency: 'next_morning',
    title: 'Circadian Anchor Protocol',
    mechanism: 'Late bedtime shifts the circadian phase. Morning bright light exposure (>10,000 lux) within 30min of waking resets the suprachiasmatic nucleus (SCN) and advances the circadian phase back to normal. This is the strongest zeitgeber available.',
    instruction: 'Wake at your NORMAL time (do not sleep in). Get 10-15min direct sunlight within 30min of waking. Cold water face splash to activate trigeminal nerve → cortisol awakening response. This prevents the phase delay from becoming chronic.',
    icon: '☀️',
    accentColor: '#FFD700',
    durationMin: 15,
    suggestedTime: 'Within 30min of waking',
    confidence: 94,
    targetBiomarkers: ['vitaminD', 'cortisol'],
    tags: ['circadian', 'sunlight', 'phase-reset'],
  }],

  /* ── Recovery Gap → Immediate Intervention ── */
  recovery_protocol_gap: (d, input) => {
    const adjustments: ReactiveAdjustment[] = [];
    adjustments.push({
      id: `${d.id}_cold_exposure`,
      disruptionId: d.id,
      targetDomain: 'holistic',
      urgency: 'immediate',
      title: 'Cold Exposure Recovery',
      mechanism: 'HRV depression indicates sympathetic overdrive. Cold exposure (2-3min) triggers the dive reflex — a powerful parasympathetic activation that increases vagal tone within minutes. Norepinephrine release also provides anti-inflammatory and mood benefits.',
      instruction: 'Cold shower: 2-3 minutes at coldest setting. Focus on face and chest (vagal nerve density). If cold plunge available: 50-55°F for 2 minutes. Breathe slowly through the nose.',
      icon: '❄️',
      accentColor: '#00FFCC',
      durationMin: 3,
      suggestedTime: 'Now',
      confidence: 89,
      targetBiomarkers: ['crp'],
      tags: ['cold', 'vagal', 'recovery'],
    });

    adjustments.push({
      id: `${d.id}_breathwork`,
      disruptionId: d.id,
      targetDomain: 'holistic',
      urgency: 'immediate',
      title: 'Vagal Tone Breathwork',
      mechanism: 'Extended exhale breathing (4-7-8 pattern) directly stimulates the vagus nerve via diaphragmatic pressure changes. This shifts autonomic balance from sympathetic to parasympathetic within 5 minutes, measurably increasing HRV.',
      instruction: '5 minutes of 4-7-8 breathing: Inhale 4 seconds through nose, hold 7 seconds, exhale 8 seconds through mouth. Repeat 6-8 cycles. Do this before any other recovery protocol.',
      icon: '🌬️',
      accentColor: '#AF82FF',
      durationMin: 5,
      suggestedTime: 'Now',
      confidence: 91,
      targetBiomarkers: ['cortisol'],
      tags: ['breathwork', 'vagal', 'parasympathetic'],
    });

    return adjustments;
  },

  /* ── Inflammation Without Cold → Targeted Intervention ── */
  inflammation_no_cold: (d) => [{
    id: `${d.id}_cold_anti_inflam`,
    disruptionId: d.id,
    targetDomain: 'holistic',
    urgency: 'immediate',
    title: 'Anti-Inflammatory Cold Protocol',
    mechanism: 'Cold immersion triggers a 200-300% increase in norepinephrine, which directly inhibits NF-κB — the master inflammatory transcription factor. This is the fastest non-pharmacological anti-inflammatory intervention available.',
    instruction: 'Cold plunge 2-3 minutes at 50-55°F. If unavailable: cold shower for 3 minutes, focusing on upper body. Follow with 5 minutes of nasal breathing to extend the parasympathetic response.',
    icon: '🧊',
    accentColor: '#00FFCC',
    durationMin: 5,
    suggestedTime: 'Morning or post-workout',
    confidence: 88,
    targetBiomarkers: ['crp'],
    tags: ['cold', 'inflammation', 'norepinephrine'],
  }],

  /* ── No Sunlight → Photonic Recovery ── */
  no_sunlight_protocol: (d) => [{
    id: `${d.id}_sunlight_rx`,
    disruptionId: d.id,
    targetDomain: 'holistic',
    urgency: 'immediate',
    title: 'Morning Sunlight Prescription',
    mechanism: 'Morning sunlight (>10,000 lux) hitting the retina triggers melanopsin → SCN signaling that sets the entire circadian cascade: cortisol awakening response, melatonin timing, and body temperature rhythm. This is the single most important daily health behavior.',
    instruction: 'Get outside within 30 minutes of waking. No sunglasses. Face the sun (don\'t stare directly). 10-15 minutes minimum. Overcast days still provide 10,000+ lux — go outside regardless of weather.',
    icon: '☀️',
    accentColor: '#FFD700',
    durationMin: 15,
    suggestedTime: 'Within 30min of waking',
    confidence: 96,
    targetBiomarkers: ['vitaminD', 'cortisol'],
    tags: ['sunlight', 'circadian', 'vitamin-d'],
  }],
};

/* ══════════════════════════════════════════════════════════════════
   COHERENCE SCORING
   
   Measures how well the three domains are synchronized.
   100 = perfect alignment, 0 = total dysregulation.
   ══════════════════════════════════════════════════════════════════ */

function computeCoherenceScore(disruptions: Disruption[], input: SynthesizerInput): number {
  let score = 100;

  // Deduct for each disruption based on severity
  const severityPenalty: Record<DisruptionSeverity, number> = { mild: 5, moderate: 12, severe: 20 };
  for (const d of disruptions) {
    score -= severityPenalty[d.severity];
  }

  // Bonus for good sleep
  if (input.sleep.hours != null && input.sleep.hours >= 7.5) score += 5;
  if (input.sleep.score != null && input.sleep.score >= 80) score += 5;

  // Bonus for HRV above baseline
  if (input.hrv.current && input.hrv.avg7d && input.hrv.current > input.hrv.avg7d * 1.05) score += 5;

  // Bonus for recovery protocols done
  const recoveryDone = input.protocolsCompleted.filter(p =>
    ['biohacking', 'recovery'].includes(p.category)
  ).length;
  score += Math.min(recoveryDone * 3, 10);

  // Bonus for protein on track
  const totalProtein = input.foodLogs.reduce((s, f) => s + f.protein, 0);
  const targetProtein = input.vitals?.weight ? input.vitals.weight * 0.82 : 130;
  if (totalProtein >= targetProtein * 0.8) score += 5;

  return Math.max(0, Math.min(100, Math.round(score)));
}

/* ══════════════════════════════════════════════════════════════════
   CONCIERGE MESSAGE GENERATOR
   
   Produces a natural-language summary that feels like a personal
   health concierge speaking to you.
   ══════════════════════════════════════════════════════════════════ */

function generateConciergeMessage(
  disruptions: Disruption[],
  adjustments: ReactiveAdjustment[],
  coherence: number,
  input: SynthesizerInput,
): string {
  if (disruptions.length === 0) {
    if (coherence >= 90) {
      return 'All three domains — nutrition, circadian rhythm, and recovery — are synchronized. Maintain current protocol cadence. Your biological systems are operating in coherence.';
    }
    return 'No acute disruptions detected. Continue current protocols and monitor for emerging patterns.';
  }

  const severe = disruptions.filter(d => d.severity === 'severe');
  const moderate = disruptions.filter(d => d.severity === 'moderate');
  const immediateAdj = adjustments.filter(a => a.urgency === 'immediate');
  const morningAdj = adjustments.filter(a => a.urgency === 'next_morning');

  const parts: string[] = [];

  if (severe.length > 0) {
    parts.push(`${severe.length} critical disruption${severe.length > 1 ? 's' : ''} detected: ${severe.map(s => s.signal).join(', ')}.`);
  }
  if (moderate.length > 0) {
    parts.push(`${moderate.length} moderate signal${moderate.length > 1 ? 's' : ''} flagged.`);
  }

  if (immediateAdj.length > 0) {
    parts.push(`${immediateAdj.length} immediate adjustment${immediateAdj.length > 1 ? 's' : ''} queued — starting with "${immediateAdj[0].title}".`);
  }
  if (morningAdj.length > 0) {
    parts.push(`${morningAdj.length} morning protocol${morningAdj.length > 1 ? 's' : ''} staged for tomorrow.`);
  }

  parts.push(`System coherence: ${coherence}/100.`);

  return parts.join(' ');
}

/* ══════════════════════════════════════════════════════════════════
   MAIN SYNTHESIZER FUNCTION
   ══════════════════════════════════════════════════════════════════ */

export function runWellnessSynthesizer(input: SynthesizerInput): SynthesizerReport {
  const now = Date.now();

  // 1. Detect disruptions across all three domains
  const disruptions: Disruption[] = [];
  for (const rule of DISRUPTION_RULES) {
    const result = rule.detect(input);
    if (result) disruptions.push(result);
  }

  // Sort by severity: severe → moderate → mild
  const severityOrder: Record<DisruptionSeverity, number> = { severe: 0, moderate: 1, mild: 2 };
  disruptions.sort((a, b) => severityOrder[a.severity] - severityOrder[b.severity]);

  // 2. Generate reactive adjustments for each disruption
  const adjustments: ReactiveAdjustment[] = [];
  for (const disruption of disruptions) {
    const generator = ADJUSTMENT_MAP[disruption.id];
    if (generator) {
      const adjs = generator(disruption, input);
      adjustments.push(...adjs);
    }
  }

  // Sort adjustments: immediate → next_morning → within_24h → ongoing
  const urgencyOrder: Record<AdjustmentUrgency, number> = { immediate: 0, next_morning: 1, within_24h: 2, ongoing: 3 };
  adjustments.sort((a, b) => urgencyOrder[a.urgency] - urgencyOrder[b.urgency]);

  // 3. Compute coherence score
  const coherenceScore = computeCoherenceScore(disruptions, input);

  // 4. Generate concierge message
  const conciergeMessage = generateConciergeMessage(disruptions, adjustments, coherenceScore, input);

  return {
    disruptions,
    adjustments,
    coherenceScore,
    conciergeMessage,
    synthesizedAt: now,
  };
}

/* ══════════════════════════════════════════════════════════════════
   HELPER: Build SynthesizerInput from raw Convex data
   
   Used by the AI Brain action to construct the input object
   from database queries.
   ══════════════════════════════════════════════════════════════════ */

export function buildSynthesizerInput(params: {
  foodLogs: any[];
  bioVault: any;
  protocolLogs: any[];
  protocolCompletions: any[];
  sleepLog: any;
  vitals: any;
}): SynthesizerInput {
  const { foodLogs, bioVault, protocolLogs, protocolCompletions, sleepLog, vitals } = params;

  return {
    foodLogs: (foodLogs ?? []).map((f: any) => ({
      name: f.name ?? 'Unknown',
      calories: f.calories ?? 0,
      protein: f.protein ?? 0,
      carbs: f.carbs ?? 0,
      fat: f.fat ?? 0,
      loggedAt: f.loggedAt ?? Date.now(),
    })),
    sleep: {
      score: bioVault?.sleepScore ?? sleepLog?.sleepScore,
      hours: bioVault?.sleepHours ?? sleepLog?.totalHours,
      deepPct: bioVault?.sleepDeepPct ?? (sleepLog ? Math.round((sleepLog.deepHours / sleepLog.totalHours) * 100) : undefined),
      remPct: bioVault?.sleepRemPct ?? (sleepLog ? Math.round((sleepLog.remHours / sleepLog.totalHours) * 100) : undefined),
      efficiency: bioVault?.sleepEfficiency ?? sleepLog?.efficiency,
      latencyMin: bioVault?.sleepLatencyMin ?? sleepLog?.latencyMin,
      bedtimeAt: sleepLog?.bedtimeAt,
      wakeAt: sleepLog?.wakeAt,
    },
    hrv: {
      current: bioVault?.hrvCurrent,
      avg7d: bioVault?.hrvAvg7d,
      trend: bioVault?.hrvTrend,
      baseline: bioVault?.hrvBaseline,
    },
    caffeine: {
      todayMg: bioVault?.caffeineTodayMg,
      lastIntakeAt: bioVault?.caffeineLastIntakeAt,
      sensitivity: bioVault?.caffeineSensitivity,
      dailyLimitMg: bioVault?.caffeineDailyLimitMg,
    },
    protocolsCompleted: (protocolCompletions ?? [])
      .filter((c: any) => c.completed)
      .map((c: any) => ({
        name: c.protocolName ?? '',
        category: c.category ?? '',
        completedAt: c.completedAt ?? Date.now(),
      })),
    protocolLogs: (protocolLogs ?? []).map((l: any) => ({
      protocolName: l.protocolName ?? '',
      category: l.category ?? '',
      loggedAt: l.loggedAt ?? Date.now(),
    })),
    bioVault: {
      crp: bioVault?.crp,
      hba1c: bioVault?.hba1c,
      vitaminD: bioVault?.vitaminD,
      testosteroneTotal: bioVault?.testosteroneTotal,
      ferritin: bioVault?.ferritin,
      caffeineSensitivity: bioVault?.caffeineSensitivity,
      mthfrVariant: bioVault?.mthfrVariant,
      apoe4: bioVault?.apoe4,
    },
    currentHour: new Date().getHours(),
    vitals: vitals ? {
      age: vitals.age,
      weight: vitals.weight,
      gender: vitals.gender,
    } : undefined,
  };
}
