import type { ChapterDef, Insight } from './types';

export const chapters: ChapterDef[] = [
  { id: 'dietary', number: 1, title: 'Dietary Needs', subtitle: 'How your body processes food', icon: '\u{1F96C}', accentColor: '#FFB86B' },
  { id: 'physical', number: 2, title: 'Physical Strengths', subtitle: 'What your muscles are built for', icon: '\u{26A1}', accentColor: '#00FFCC' },
  { id: 'risks', number: 3, title: 'Health Risks', subtitle: 'What to watch and protect', icon: '\u{1F6E1}\uFE0F', accentColor: '#FF6BB5' },
];

export const insights: Insight[] = [
  /* ── Chapter 1: Dietary Needs ── */
  {
    chapter: 'dietary',
    humanTitle: 'Caffeine Sensitivity',
    tagline: 'How fast you metabolize your morning coffee',
    icon: '\u2615',
    accentColor: '#FFB86B',
    whatItMeans: 'Your body breaks down caffeine slower than average. That afternoon espresso might still be in your system at bedtime, disrupting deep sleep cycles and recovery.',
    yourResult: 'Slow Metabolizer',
    resultBadge: 'Limit after 12pm',
    actionItems: [
      'Cap caffeine at 200mg before noon \u2014 roughly one strong coffee',
      'Switch to green tea after lunch for gentle, sustained focus',
      'Allow 8+ hours between last caffeine and sleep',
      'Consider L-theanine (200mg) to smooth out any jitters',
    ],
    confidence: 94,
  },
  {
    chapter: 'dietary',
    humanTitle: 'Fat Processing',
    tagline: 'How your body handles dietary fats',
    icon: '\u{1F951}',
    accentColor: '#FFB86B',
    whatItMeans: 'You have a moderate predisposition to weight gain with high-fat diets. Your metabolic flexibility is partially compromised, meaning your body is slower to switch between burning carbs and fats for fuel.',
    yourResult: 'Moderate Sensitivity',
    resultBadge: 'Favor healthy fats',
    actionItems: [
      'Keep saturated fat under 10% of daily calories',
      'Prioritize omega-3 sources: salmon, sardines, walnuts',
      'Try carb cycling \u2014 higher carbs on training days, lower on rest days',
      'Monitor fasting glucose quarterly \u2014 aim for under 90 mg/dL',
    ],
    confidence: 88,
  },
  {
    chapter: 'dietary',
    humanTitle: 'Salt Processing',
    tagline: 'How sodium affects your blood pressure',
    icon: '\u{1F9C2}',
    accentColor: '#FFB86B',
    whatItMeans: 'Your genetics indicate higher salt sensitivity. Excess sodium has a stronger-than-average effect on your blood pressure, which means dietary sodium management is especially important for you.',
    yourResult: 'Salt Sensitive',
    resultBadge: 'Watch intake',
    actionItems: [
      'Target under 2,000mg sodium per day (vs. the 2,300mg general guideline)',
      'Read labels \u2014 processed foods are the #1 hidden sodium source',
      'Increase potassium-rich foods: bananas, sweet potatoes, spinach',
      'Use herbs and spices instead of salt for flavoring',
    ],
    confidence: 82,
  },

  /* ── Chapter 2: Physical Strengths ── */
  {
    chapter: 'physical',
    humanTitle: 'Power & Sprint Ability',
    tagline: 'Your fast-twitch muscle potential',
    icon: '\u{1F3C3}',
    accentColor: '#00FFCC',
    whatItMeans: 'You carry the genetic profile associated with elite sprint and power athletes. Your fast-twitch muscle fibers are fully expressed, giving you an advantage in explosive movements like sprinting, jumping, and heavy lifting.',
    yourResult: 'Enhanced Power',
    resultBadge: 'Elite potential',
    actionItems: [
      'Prioritize explosive training: plyometrics, Olympic lifts, sprint intervals',
      'Supplement with creatine monohydrate (5g/day) for phosphocreatine stores',
      'Allow 48-72 hours recovery between maximal power sessions',
      'Add beta-alanine (3.2g/day) for high-intensity buffering',
    ],
    confidence: 96,
  },
  {
    chapter: 'physical',
    humanTitle: 'Endurance Capacity',
    tagline: 'How well you sustain long efforts',
    icon: '\u{1F6B4}',
    accentColor: '#00FFCC',
    whatItMeans: 'Your aerobic engine is solid but not exceptional. You can build great endurance with consistent training, but your genetic ceiling favors moderate-duration efforts over ultra-endurance events.',
    yourResult: 'Above Average',
    resultBadge: 'Trainable',
    actionItems: [
      'Build an aerobic base with Zone 2 training (3-4 sessions/week)',
      'Include one tempo run or threshold session weekly',
      'Focus on mitochondrial density through steady-state cardio',
      'Supplement with CoQ10 (200mg/day) for cellular energy production',
    ],
    confidence: 79,
  },
  {
    chapter: 'physical',
    humanTitle: 'Recovery Speed',
    tagline: 'How quickly your muscles bounce back',
    icon: '\u{1F4A4}',
    accentColor: '#00FFCC',
    whatItMeans: 'Your recovery genetics are favorable. You clear metabolic waste efficiently and your inflammatory response resolves faster than average, meaning you can handle higher training frequency.',
    yourResult: 'Fast Recovery',
    resultBadge: 'Advantage',
    actionItems: [
      'You can train the same muscle group every 48 hours if nutrition is dialed in',
      'Prioritize 7-9 hours of sleep for optimal growth hormone release',
      'Use tart cherry juice (8oz post-workout) to further reduce inflammation',
      'Cold exposure (2-3 min cold shower) can accelerate recovery on heavy days',
    ],
    confidence: 91,
  },

  /* ── Chapter 3: Health Risks ── */
  {
    chapter: 'risks',
    humanTitle: 'Oxidative Stress Defense',
    tagline: 'How well your cells fight free radicals',
    icon: '\u{1F6E1}\uFE0F',
    accentColor: '#FF6BB5',
    whatItMeans: 'Your mitochondrial antioxidant enzyme works at about 60-70% efficiency. Under high training loads or chronic stress, free radicals can accumulate faster than your body neutralizes them, accelerating cellular aging.',
    yourResult: 'Reduced Defense',
    resultBadge: 'Needs support',
    actionItems: [
      'Supplement with MitoQ or ubiquinol (200mg/day) for mitochondrial protection',
      'Increase vitamin C (500mg) and vitamin E (mixed tocopherols) daily',
      'Cap high-intensity sessions at 3-4 per week to manage oxidative load',
      'Add NAC (600mg twice daily) to support glutathione recycling',
    ],
    confidence: 85,
  },
  {
    chapter: 'risks',
    humanTitle: 'Brain Health Outlook',
    tagline: 'Your cognitive aging trajectory',
    icon: '\u{1F9E0}',
    accentColor: '#6B8AFF',
    whatItMeans: 'Great news \u2014 you carry the most common and lowest-risk variant for cognitive aging. No elevated genetic risk for Alzheimer\'s or accelerated cognitive decline was detected in your profile.',
    yourResult: 'Standard Risk',
    resultBadge: 'All clear',
    actionItems: [
      'Maintain DHA intake (1-2g/day) from wild-caught fish or algae oil',
      'Practice cognitive challenges: puzzles, learning new skills, dual n-back',
      'Prioritize consistent sleep for glymphatic brain clearance',
      'Include polyphenol-rich foods: blueberries, dark chocolate, green tea',
    ],
    confidence: 92,
  },
  {
    chapter: 'risks',
    humanTitle: 'Heart Health Profile',
    tagline: 'Your cardiovascular genetic markers',
    icon: '\u2764\uFE0F',
    accentColor: '#FF6BB5',
    whatItMeans: 'Your lipid metabolism genes show a slight tendency toward elevated LDL cholesterol. This is manageable with diet and lifestyle, but worth monitoring annually with a full lipid panel.',
    yourResult: 'Mild Elevation Risk',
    resultBadge: 'Monitor yearly',
    actionItems: [
      'Get a comprehensive lipid panel annually (include ApoB and Lp(a))',
      'Increase soluble fiber: oats, beans, flaxseed (aim for 25-30g/day total fiber)',
      'Include plant sterols from nuts and seeds to naturally lower LDL',
      'Maintain regular cardio \u2014 150+ minutes moderate activity per week',
    ],
    confidence: 77,
  },
];
