import React, { useState, useEffect, useMemo } from 'react';

/* ══════════════════════════════════════════════════════════════ */
/*  COMMAND DIRECTIVE — Daily Clinical Checklist                  */
/*  Auto-generates directives based on biometric gauge readings   */
/* ══════════════════════════════════════════════════════════════ */

interface Directive {
  id: string;
  label: string;
  category: 'recovery' | 'performance' | 'nutrition' | 'mindset';
  priority: 'critical' | 'high' | 'standard';
  autoGenerated?: boolean;
  triggerReason?: string;
}

const CATEGORY_COLORS: Record<string, string> = {
  recovery: '#00FFCC',
  performance: '#00B4FF',
  nutrition: '#FFB86B',
  mindset: '#C084FC',
};

const PRIORITY_INDICATOR: Record<string, string> = {
  critical: '▲▲',
  high: '▲',
  standard: '·',
};

const BASE_DIRECTIVES: Directive[] = [
  { id: 'hydration', label: 'Hydration Protocol — 3.5L minimum', category: 'nutrition', priority: 'standard' },
  { id: 'sunlight', label: 'Morning Sunlight Exposure (10 min)', category: 'mindset', priority: 'standard' },
  { id: 'protein', label: 'Protein Target — 1g/lb bodyweight', category: 'nutrition', priority: 'high' },
  { id: 'mobility', label: 'Joint Mobility Sequence (5 min)', category: 'recovery', priority: 'standard' },
];

function getAutoDirectives(sleepScore: number, activityScore: number): Directive[] {
  const auto: Directive[] = [];

  if (sleepScore < 70) {
    auto.push({
      id: 'mag-threonate',
      label: 'Magnesium L-Threonate (400mg)',
      category: 'recovery',
      priority: 'critical',
      autoGenerated: true,
      triggerReason: `Sleep gauge at ${sleepScore}% — below threshold`,
    });
  }
  if (sleepScore < 70) {
    auto.push({
      id: 'blue-light',
      label: 'Blue Light Block — 2hrs before sleep',
      category: 'recovery',
      priority: 'high',
      autoGenerated: true,
      triggerReason: `Sleep recovery protocol`,
    });
  }

  if (activityScore < 60) {
    auto.push({
      id: 'zone2-recovery',
      label: 'Zone 2 Recovery (30 min)',
      category: 'performance',
      priority: 'critical',
      autoGenerated: true,
      triggerReason: `Activity gauge at ${activityScore}% — movement deficit`,
    });
  }
  if (activityScore < 50) {
    auto.push({
      id: 'walk-10k',
      label: 'Minimum 10,000 Steps Today',
      category: 'performance',
      priority: 'high',
      autoGenerated: true,
      triggerReason: `Activity critically low`,
    });
  }

  return auto;
}

export function CommandDirective({
  sleepScore = 62,
  activityScore = 45,
}: {
  sleepScore?: number;
  activityScore?: number;
}) {
  const [completed, setCompleted] = useState<Set<string>>(new Set());
  const [mounted, setMounted] = useState(false);

  useEffect(() => { setMounted(true); }, []);

  const autoDirectives = useMemo(
    () => getAutoDirectives(sleepScore, activityScore),
    [sleepScore, activityScore]
  );

  const allDirectives = useMemo(
    () => [...autoDirectives, ...BASE_DIRECTIVES],
    [autoDirectives]
  );

  const completedCount = completed.size;
  const totalCount = allDirectives.length;
  const completionPct = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;

  const toggleDirective = (id: string) => {
    setCompleted(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  };

  const statusColor = completionPct === 100 ? '#00FFCC' : completionPct >= 50 ? '#FFB86B' : '#FF6B6B';
  const statusLabel = completionPct === 100 ? 'COMPLETE' : completionPct >= 50 ? 'IN PROGRESS' : 'ACTIVE';

  return (
    <div
      className="rounded-2xl overflow-hidden"
      style={{
        background: 'rgba(8,10,12,0.85)',
        border: '1px solid rgba(0,240,255,0.08)',
        backdropFilter: 'blur(20px)',
        opacity: mounted ? 1 : 0,
        transform: mounted ? 'translateY(0)' : 'translateY(8px)',
        transition: 'opacity 0.5s ease, transform 0.5s ease',
      }}
    >
      {/* Header */}
      <div className="px-4 pt-4 pb-3 flex items-center justify-between">
        <div className="flex items-center gap-2.5">
          <div
            className="w-2 h-2 rounded-full"
            style={{
              background: statusColor,
              boxShadow: `0 0 8px ${statusColor}66`,
              animation: completionPct < 100 ? 'pulse 2s ease-in-out infinite' : undefined,
            }}
          />
          <span
            className="text-[11px] tracking-[3px] uppercase"
            style={{ color: 'rgba(0,240,255,0.5)', fontFamily: 'ui-monospace, monospace' }}
          >
            Daily Directives
          </span>
        </div>
        <div className="flex items-center gap-2">
          <span
            className="text-[10px] tracking-[2px] uppercase"
            style={{ color: statusColor, fontFamily: 'ui-monospace, monospace' }}
          >
            {statusLabel}
          </span>
          <span
            className="text-[10px] tabular-nums"
            style={{ color: 'rgba(0,240,255,0.35)', fontFamily: 'ui-monospace, monospace' }}
          >
            {completedCount}/{totalCount}
          </span>
        </div>
      </div>

      {/* Progress bar */}
      <div className="mx-4 h-[2px] rounded-full overflow-hidden" style={{ background: 'rgba(0,240,255,0.06)' }}>
        <div
          className="h-full rounded-full"
          style={{
            width: `${completionPct}%`,
            background: `linear-gradient(90deg, ${statusColor}, ${statusColor}88)`,
            boxShadow: `0 0 8px ${statusColor}44`,
            transition: 'width 0.6s cubic-bezier(0.4,0,0.2,1)',
          }}
        />
      </div>

      {/* Directive list */}
      <div className="px-3 py-2 flex flex-col gap-0.5">
        {allDirectives.map((d, i) => {
          const done = completed.has(d.id);
          const catColor = CATEGORY_COLORS[d.category] ?? '#00FFCC';
          const isCritical = d.priority === 'critical';

          return (
            <button
              key={d.id}
              onClick={() => toggleDirective(d.id)}
              className="w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-left group"
              style={{
                background: done
                  ? 'rgba(0,255,204,0.04)'
                  : isCritical
                    ? 'rgba(255,107,107,0.04)'
                    : 'transparent',
                border: `1px solid ${
                  done
                    ? 'rgba(0,255,204,0.12)'
                    : isCritical
                      ? 'rgba(255,107,107,0.1)'
                      : 'rgba(0,240,255,0.04)'
                }`,
                opacity: mounted ? 1 : 0,
                transform: mounted ? 'translateX(0)' : 'translateX(-8px)',
                transition: `all 0.3s ease ${i * 0.05}s`,
                minHeight: 44,
              }}
            >
              {/* Checkbox */}
              <div
                className="w-4 h-4 rounded-sm flex items-center justify-center flex-shrink-0"
                style={{
                  border: `1.5px solid ${done ? '#00FFCC' : 'rgba(0,240,255,0.2)'}`,
                  background: done ? 'rgba(0,255,204,0.15)' : 'transparent',
                  transition: 'all 0.2s ease',
                }}
              >
                {done && (
                  <svg width="10" height="10" viewBox="0 0 10 10" fill="none">
                    <path d="M2 5L4 7L8 3" stroke="#00FFCC" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                )}
              </div>

              {/* Priority indicator */}
              <span
                className="text-[9px] w-4 text-center flex-shrink-0"
                style={{
                  color: isCritical ? '#FF6B6B' : d.priority === 'high' ? '#FFB86B' : 'rgba(0,240,255,0.2)',
                  fontFamily: 'ui-monospace, monospace',
                }}
              >
                {PRIORITY_INDICATOR[d.priority]}
              </span>

              {/* Label */}
              <div className="flex-1 min-w-0">
                <span
                  className="text-[12px] leading-tight block"
                  style={{
                    color: done ? 'rgba(0,255,204,0.5)' : 'rgba(224,220,216,0.85)',
                    fontFamily: 'ui-monospace, monospace',
                    textDecoration: done ? 'line-through' : 'none',
                    transition: 'color 0.2s, text-decoration 0.2s',
                  }}
                >
                  {d.label}
                </span>
                {d.autoGenerated && d.triggerReason && !done && (
                  <span
                    className="text-[9px] block mt-0.5 tracking-wide"
                    style={{
                      color: isCritical ? 'rgba(255,107,107,0.5)' : 'rgba(0,240,255,0.3)',
                      fontFamily: 'ui-monospace, monospace',
                    }}
                  >
                    ⚡ {d.triggerReason}
                  </span>
                )}
              </div>

              {/* Category tag */}
              <span
                className="text-[8px] tracking-[1.5px] uppercase px-1.5 py-0.5 rounded flex-shrink-0"
                style={{
                  color: `${catColor}88`,
                  background: `${catColor}0A`,
                  border: `1px solid ${catColor}15`,
                  fontFamily: 'ui-monospace, monospace',
                }}
              >
                {d.category.slice(0, 3)}
              </span>
            </button>
          );
        })}
      </div>

      {/* Footer */}
      <div
        className="px-4 py-2.5 flex items-center justify-between"
        style={{ borderTop: '1px solid rgba(0,240,255,0.04)' }}
      >
        <span
          className="text-[9px] tracking-[2px] uppercase"
          style={{ color: 'rgba(0,240,255,0.25)', fontFamily: 'ui-monospace, monospace' }}
        >
          {autoDirectives.length > 0
            ? `${autoDirectives.length} auto-generated from biometrics`
            : 'All systems nominal'}
        </span>
        <span
          className="text-[10px] tabular-nums"
          style={{
            color: statusColor,
            fontFamily: 'ui-monospace, monospace',
            textShadow: `0 0 8px ${statusColor}44`,
          }}
        >
          {completionPct}%
        </span>
      </div>
    </div>
  );
}

export default CommandDirective;
