/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as BiovaultSettingsRouteImport } from './routes/biovault-settings'
import { Route as BiovaultRouteImport } from './routes/biovault'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsConnectionsRouteImport } from './routes/settings/connections'
import { Route as OnboardingPersonalizeRouteImport } from './routes/onboarding/personalize'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BiovaultSettingsRoute = BiovaultSettingsRouteImport.update({
  id: '/biovault-settings',
  path: '/biovault-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BiovaultRoute = BiovaultRouteImport.update({
  id: '/biovault',
  path: '/biovault',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/settings/connections',
  path: '/settings/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPersonalizeRoute = OnboardingPersonalizeRouteImport.update({
  id: '/personalize',
  path: '/personalize',
  getParentRoute: () => OnboardingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biovault': typeof BiovaultRoute
  '/biovault-settings': typeof BiovaultSettingsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/onboarding/personalize': typeof OnboardingPersonalizeRoute
  '/settings/connections': typeof SettingsConnectionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biovault': typeof BiovaultRoute
  '/biovault-settings': typeof BiovaultSettingsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/onboarding/personalize': typeof OnboardingPersonalizeRoute
  '/settings/connections': typeof SettingsConnectionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biovault': typeof BiovaultRoute
  '/biovault-settings': typeof BiovaultSettingsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/onboarding/personalize': typeof OnboardingPersonalizeRoute
  '/settings/connections': typeof SettingsConnectionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biovault'
    | '/biovault-settings'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/onboarding/personalize'
    | '/settings/connections'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biovault'
    | '/biovault-settings'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/onboarding/personalize'
    | '/settings/connections'
  id:
    | '__root__'
    | '/'
    | '/biovault'
    | '/biovault-settings'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/onboarding/personalize'
    | '/settings/connections'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiovaultRoute: typeof BiovaultRoute
  BiovaultSettingsRoute: typeof BiovaultSettingsRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biovault-settings': {
      id: '/biovault-settings'
      path: '/biovault-settings'
      fullPath: '/biovault-settings'
      preLoaderRoute: typeof BiovaultSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biovault': {
      id: '/biovault'
      path: '/biovault'
      fullPath: '/biovault'
      preLoaderRoute: typeof BiovaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/personalize': {
      id: '/onboarding/personalize'
      path: '/personalize'
      fullPath: '/onboarding/personalize'
      preLoaderRoute: typeof OnboardingPersonalizeRouteImport
      parentRoute: typeof OnboardingRoute
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingPersonalizeRoute: typeof OnboardingPersonalizeRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingPersonalizeRoute: OnboardingPersonalizeRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiovaultRoute: BiovaultRoute,
  BiovaultSettingsRoute: BiovaultSettingsRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
